spring:
  profiles:
    active: dev
    group:
      dev:
        - db-dev
      test:
        - db-test

  jpa:
    open-in-view: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

server:
  port: 8080

logging:
  level:
    root: INFO
    com.climbx: INFO