spring:
  config:
    activate:
      on-profile: db-test

  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/climbx_test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USER:test_user}
    password: ${MYSQL_PASSWORD:test_password}
    
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-timeout: 10000
      
  # testing with H2 inmemory DB setttings
  # datasource:
  #   driver-class-name: org.h2.Driver
  #   url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  #   username: sa
  #   password: 
  # h2:
  #   console:
  #     enabled: true 