spring:
  config:
    activate:
      on-profile: test

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.climbx: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
    # 테스트 환경에서는 더 조용한 로깅도 가능
    # org.springframework.test: INFO
    # org.testcontainers: INFO 